-- SAHEB ERP production schema for Supabase PostgreSQL
create extension if not exists pgcrypto;

create type country_code as enum ('SA', 'AE');
create type record_status as enum ('draft', 'active', 'inactive', 'approved', 'rejected');
create type approval_status as enum ('pending', 'approved', 'rejected', 'cancelled');
create type transaction_direction as enum ('in', 'out', 'transfer');
create type user_role as enum ('owner', 'admin', 'finance', 'sales', 'warehouse', 'payroll', 'auditor');

create table companies (
  id uuid primary key default gen_random_uuid(),
  name_ar text not null,
  name_en text,
  country country_code not null,
  currency char(3) not null default 'SAR',
  status record_status not null default 'active',
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table company_memberships (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references companies(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role user_role not null default 'auditor',
  branch_ids uuid[] not null default '{}',
  created_at timestamptz not null default now(),
  unique(company_id, user_id)
);

create table company_vat_numbers (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references companies(id) on delete cascade,
  country country_code not null,
  vat_number text not null,
  legal_name text,
  is_default boolean not null default false,
  starts_on date,
  ends_on date,
  unique(company_id, vat_number)
);

create table branches (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, name_ar text not null, name_en text, country country_code not null, city text, status record_status not null default 'active', metadata jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table warehouses (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, branch_id uuid references branches(id), name_ar text not null, name_en text, status record_status not null default 'active', metadata jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table customers (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, vat_number text, credit_limit numeric(18,2) default 0, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table suppliers (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, vat_number text, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table inventory_items (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), warehouse_id uuid references warehouses(id), sku text not null, barcode text, name_ar text not null, name_en text, vat_rate numeric(5,2) default 15, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now(), unique(company_id, sku));
create table inventory_movements (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), warehouse_id uuid references warehouses(id), item_id uuid references inventory_items(id), direction transaction_direction not null, quantity numeric(18,3) not null, unit_cost numeric(18,2), name_ar text not null default 'حركة مخزون', name_en text, metadata jsonb default '{}', status record_status default 'active', created_at timestamptz default now(), updated_at timestamptz default now());
create table sales_invoices (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), warehouse_id uuid references warehouses(id), customer_id uuid references customers(id), invoice_no text not null, issue_date date not null default current_date, subtotal numeric(18,2) default 0, vat_total numeric(18,2) default 0, total numeric(18,2) default 0, status record_status default 'draft', name_ar text not null, name_en text, metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now(), unique(company_id, invoice_no));
create table purchase_invoices (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), warehouse_id uuid references warehouses(id), supplier_id uuid references suppliers(id), invoice_no text not null, issue_date date default current_date, subtotal numeric(18,2) default 0, vat_total numeric(18,2) default 0, total numeric(18,2) default 0, status record_status default 'draft', name_ar text not null, name_en text, metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table chart_accounts (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), code text not null, name_ar text not null, name_en text, account_type text not null, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now(), unique(company_id, code));
create table journal_entries (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, entry_date date default current_date, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table cashboxes (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, currency char(3) default 'SAR', balance numeric(18,2) default 0, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table bank_accounts (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, iban text, currency char(3) default 'SAR', balance numeric(18,2) default 0, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table transfers (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), warehouse_id uuid references warehouses(id), name_ar text not null, name_en text, amount numeric(18,2), status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table expenses (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, amount numeric(18,2) not null default 0, vat_amount numeric(18,2) default 0, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table employees (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, national_id text, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table payroll_runs (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, period_start date not null, period_end date not null, total_amount numeric(18,2) default 0, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table projects (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, budget numeric(18,2) default 0, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table investments (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, asset_class text, fair_value numeric(18,2) default 0, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table attachments (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, bucket text not null default 'erp-attachments', path text not null default '', status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table notifications (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, recipient_id uuid references auth.users(id), read_at timestamptz, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table approvals (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, subject_table text not null, subject_id uuid, approval_status approval_status default 'pending', status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table activity_logs (id uuid primary key default gen_random_uuid(), company_id uuid references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, actor_id uuid references auth.users(id), action text not null, metadata jsonb default '{}', status record_status default 'active', created_at timestamptz default now(), updated_at timestamptz default now());
create table mobile_sales_visits (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), customer_id uuid references customers(id), name_ar text not null, name_en text, visit_at timestamptz default now(), geo jsonb default '{}', status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table ai_insights (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, insight_type text not null default 'forecast', confidence numeric(5,2), status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table wealth_snapshots (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, snapshot_date date default current_date, assets numeric(18,2) default 0, liabilities numeric(18,2) default 0, net_worth numeric(18,2) generated always as (assets - liabilities) stored, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());



create table journal_entry_lines (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), journal_entry_id uuid not null references journal_entries(id) on delete cascade, account_id uuid not null references chart_accounts(id), description text, debit numeric(18,2) not null default 0, credit numeric(18,2) not null default 0, created_at timestamptz default now(), check (debit >= 0 and credit >= 0 and not (debit > 0 and credit > 0)));
create table accounting_periods (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), name_ar text not null, starts_on date not null, ends_on date not null, closed_at timestamptz, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table sales_invoice_lines (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), sales_invoice_id uuid not null references sales_invoices(id) on delete cascade, item_id uuid references inventory_items(id), description text, quantity numeric(18,3) not null, unit_price numeric(18,2) not null, vat_rate numeric(5,2) default 15, line_total numeric(18,2) not null default 0, created_at timestamptz default now());
create table purchase_invoice_lines (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), purchase_invoice_id uuid not null references purchase_invoices(id) on delete cascade, item_id uuid references inventory_items(id), description text, quantity numeric(18,3) not null, unit_cost numeric(18,2) not null, vat_rate numeric(5,2) default 15, line_total numeric(18,2) not null default 0, created_at timestamptz default now());
create table stock_valuation_layers (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), warehouse_id uuid not null references warehouses(id), item_id uuid not null references inventory_items(id), movement_id uuid references inventory_movements(id), quantity_delta numeric(18,3) not null, unit_cost numeric(18,2) not null default 0, total_value numeric(18,2) not null default 0, created_at timestamptz default now());
create table module_permissions (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), role user_role not null, module_key text not null, can_read boolean default false, can_create boolean default false, can_update boolean default false, can_delete boolean default false, can_approve boolean default false, can_post boolean default false, can_export boolean default false, created_at timestamptz default now(), updated_at timestamptz default now(), unique(company_id, role, module_key));



create table system_settings (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), key text not null, value jsonb not null default '{}', name_ar text not null, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now(), unique(company_id, key));
create table approval_steps (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), approval_id uuid not null references approvals(id) on delete cascade, step_order int not null, approver_id uuid, role user_role, name_ar text not null, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table approval_decisions (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), approval_id uuid not null references approvals(id) on delete cascade, approver_id uuid, decision approval_status not null, notes text, name_ar text not null, created_at timestamptz default now());
create table warehouse_transfers (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), from_warehouse_id uuid not null references warehouses(id), to_warehouse_id uuid not null references warehouses(id), item_id uuid not null references inventory_items(id), quantity numeric(18,3) not null, unit_cost numeric(18,2) default 0, name_ar text not null, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table vat_documents (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), document_type text not null check (document_type in ('sale','purchase')), party_type text not null check (party_type in ('customer','supplier')), party_id uuid not null, seller_vat_id uuid, buyer_vat_id uuid, subtotal numeric(18,2) default 0, vat_rate numeric(5,2) default 15, vat_amount numeric(18,2) default 0, total numeric(18,2) default 0, name_ar text not null, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table whatsapp_orders (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), customer_phone text not null, message text not null, parsed_items jsonb default '[]', name_ar text not null, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());

create table customer_collections (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), customer_id uuid not null references customers(id), representative_id uuid, handover_id uuid, collection_no text not null, collection_date date default current_date, amount numeric(18,2) not null, method text default 'cash', name_ar text not null default 'تحصيل عميل', status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now(), unique(company_id, collection_no));
create table supplier_payments (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), supplier_id uuid not null references suppliers(id), payment_no text not null, payment_date date default current_date, amount numeric(18,2) not null, method text default 'bank', name_ar text not null default 'دفعة مورد', status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now(), unique(company_id, payment_no));
create table treasury_transfers (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), from_type text not null, from_id uuid not null, to_type text not null, to_id uuid not null, amount numeric(18,2) not null, name_ar text not null, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table cash_movements (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), transfer_id uuid references treasury_transfers(id), source_type text not null, source_id uuid not null, direction transaction_direction not null, amount numeric(18,2) not null, name_ar text not null, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table landed_cost_allocations (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), shipment_id uuid, purchase_invoice_id uuid references purchase_invoices(id), amount numeric(18,2) not null default 0, name_ar text not null, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table contract_attachments (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), contract_id uuid not null, attachment_id uuid not null references attachments(id) on delete cascade, name_ar text not null default 'مرفق عقد', status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), unique(contract_id, attachment_id));
create table cashier_handovers (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), representative_id uuid not null, cashier_id uuid not null, collection_ids uuid[] not null default '{}', total_amount numeric(18,2) not null default 0, name_ar text not null, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create or replace view customer_ledger as select company_id, branch_id, customer_id, invoice_no as document_no, issue_date as document_date, total as debit, 0::numeric as credit, status from sales_invoices union all select company_id, branch_id, customer_id, collection_no, collection_date, 0::numeric, amount, status from customer_collections;
create or replace view supplier_ledger as select company_id, branch_id, supplier_id, invoice_no as document_no, issue_date as document_date, total as credit, 0::numeric as debit, status from purchase_invoices union all select company_id, branch_id, supplier_id, payment_no, payment_date, 0::numeric, amount, status from supplier_payments;

create table customer_reconciliations (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), customer_id uuid references customers(id), name_ar text not null, name_en text, statement_date date default current_date, ledger_balance numeric(18,2) default 0, statement_balance numeric(18,2) default 0, difference_amount numeric(18,2) generated always as (ledger_balance - statement_balance) stored, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table supplier_reconciliations (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), supplier_id uuid references suppliers(id), name_ar text not null, name_en text, statement_date date default current_date, ledger_balance numeric(18,2) default 0, statement_balance numeric(18,2) default 0, difference_amount numeric(18,2) generated always as (ledger_balance - statement_balance) stored, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table dubai_shipping_shipments (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), warehouse_id uuid references warehouses(id), name_ar text not null, name_en text, awb text not null, carrier text, origin_country text, eta date, clearance_cost numeric(18,2) default 0, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now(), unique(company_id, awb));
create table main_vaults (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, currency char(3) default 'SAR', balance numeric(18,2) default 0, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table contracts (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), project_id uuid references projects(id), customer_id uuid references customers(id), supplier_id uuid references suppliers(id), name_ar text not null, name_en text, contract_no text not null, starts_on date, ends_on date, contract_value numeric(18,2) default 0, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now(), unique(company_id, contract_no));
create table role_permissions (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, role user_role not null, module_key text not null, permission text not null, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now(), unique(company_id, role, module_key, permission));
create table party_vat_numbers (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), party_type text not null check (party_type in ('seller','customer','supplier')), party_id uuid, country country_code not null, vat_number text not null, name_ar text not null, name_en text, is_default boolean default false, starts_on date, ends_on date, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now(), unique(company_id, party_type, party_id, vat_number));
create table mobile_sales_representatives (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), employee_id uuid references employees(id), name_ar text not null, name_en text, territory text, target_amount numeric(18,2) default 0, status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table ai_discrepancy_findings (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), name_ar text not null, name_en text, source_module text not null, severity text not null default 'medium', difference_amount numeric(18,2) default 0, suggested_reason text, suggested_action text, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table notification_deliveries (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), notification_id uuid references notifications(id), name_ar text not null default 'تسليم إشعار', name_en text, channel text not null default 'in_app', delivered_at timestamptz, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());


-- Production completion tables for quotations, returns, backup/import, and universal attachment links.
create table sales_quotations (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), customer_id uuid references customers(id), quotation_no text not null, issue_date date default current_date, valid_until date, subtotal numeric(18,2) default 0, vat_total numeric(18,2) default 0, total numeric(18,2) default 0, converted_invoice_id uuid references sales_invoices(id), name_ar text not null, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now(), unique(company_id, quotation_no));
create table sales_quotation_lines (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), quotation_id uuid not null references sales_quotations(id) on delete cascade, item_id uuid references inventory_items(id), description text, quantity numeric(18,3) not null, unit_price numeric(18,2) not null, vat_rate numeric(5,2) default 15, line_total numeric(18,2) not null default 0, created_at timestamptz default now());
create table sales_returns (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), warehouse_id uuid references warehouses(id), customer_id uuid references customers(id), sales_invoice_id uuid references sales_invoices(id), return_no text not null, return_date date default current_date, subtotal numeric(18,2) default 0, vat_total numeric(18,2) default 0, total numeric(18,2) default 0, name_ar text not null, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now(), unique(company_id, return_no));
create table sales_return_lines (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), sales_return_id uuid not null references sales_returns(id) on delete cascade, item_id uuid references inventory_items(id), description text, quantity numeric(18,3) not null, unit_price numeric(18,2) not null, vat_rate numeric(5,2) default 15, line_total numeric(18,2) not null default 0, created_at timestamptz default now());
create table purchase_returns (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), warehouse_id uuid references warehouses(id), supplier_id uuid references suppliers(id), purchase_invoice_id uuid references purchase_invoices(id), return_no text not null, return_date date default current_date, subtotal numeric(18,2) default 0, vat_total numeric(18,2) default 0, total numeric(18,2) default 0, name_ar text not null, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now(), unique(company_id, return_no));
create table purchase_return_lines (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), purchase_return_id uuid not null references purchase_returns(id) on delete cascade, item_id uuid references inventory_items(id), description text, quantity numeric(18,3) not null, unit_cost numeric(18,2) not null, vat_rate numeric(5,2) default 15, line_total numeric(18,2) not null default 0, created_at timestamptz default now());
create table attachment_links (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), attachment_id uuid not null references attachments(id) on delete cascade, subject_table text not null, subject_id uuid not null, name_ar text not null default 'ربط مرفق', status record_status default 'active', metadata jsonb default '{}', created_at timestamptz default now(), unique(attachment_id, subject_table, subject_id));
create table backup_jobs (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), requested_by uuid references auth.users(id), job_type text not null check (job_type in ('export','restore','import')), file_name text, checksum text, row_counts jsonb default '{}', name_ar text not null, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table import_jobs (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), requested_by uuid references auth.users(id), source_system text not null default 'external_erp', target_table text not null, file_name text, total_rows int default 0, accepted_rows int default 0, rejected_rows int default 0, errors jsonb default '[]', name_ar text not null, status record_status default 'draft', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());

create or replace function user_can_access_company(target_company uuid) returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from company_memberships where company_id = target_company and user_id = auth.uid());
$$;

create or replace function touch_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

do $$
declare r record;
begin
  for r in select tablename from pg_tables where schemaname = 'public' and tablename not like 'pg_%' loop
    execute format('alter table %I enable row level security', r.tablename);
    if r.tablename = 'companies' then
      execute 'create policy company_members_can_read on companies for select to authenticated using (user_can_access_company(id))';
    elsif r.tablename = 'company_memberships' then
      execute 'create policy members_can_read_own_memberships on company_memberships for select to authenticated using (user_id = auth.uid() or user_can_access_company(company_id))';
    elsif exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = r.tablename and column_name = 'company_id') then
      execute format('create policy tenant_isolation_select on %I for select to authenticated using (user_can_access_company(company_id))', r.tablename);
      execute format('create policy tenant_isolation_write on %I for all to authenticated using (user_can_access_company(company_id)) with check (user_can_access_company(company_id))', r.tablename);
    end if;
    if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = r.tablename and column_name = 'updated_at') then
      execute format('create trigger set_updated_at before update on %I for each row execute function touch_updated_at()', r.tablename);
    end if;
  end loop;
exception when duplicate_object then null;
end $$;

insert into storage.buckets (id, name, public) values ('erp-attachments', 'erp-attachments', false) on conflict (id) do nothing;

do $$
begin
  create policy erp_attachments_select on storage.objects for select to authenticated using (bucket_id = 'erp-attachments');
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy erp_attachments_insert on storage.objects for insert to authenticated with check (bucket_id = 'erp-attachments');
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy erp_attachments_update on storage.objects for update to authenticated using (bucket_id = 'erp-attachments') with check (bucket_id = 'erp-attachments');
exception when duplicate_object then null;
end $$;
