export type ErpModuleKey =
  | "companies" | "branches" | "warehouses" | "customers" | "customer_reconciliations" | "suppliers" | "supplier_reconciliations"
  | "dubai_shipping_office" | "inventory" | "sales" | "sales_quotations" | "sales_returns" | "purchases" | "purchase_returns" | "accounting" | "cashboxes" | "main_vault" | "banks" | "transfers"
  | "expenses" | "payroll" | "projects" | "contracts" | "investments" | "attachments" | "notifications" | "approvals" | "role_permissions"
  | "activity_logs" | "mobile_sales" | "ai_discrepancy_analysis" | "ai_analytics" | "wealth_dashboard" | "multi_vat" | "backup_jobs" | "import_jobs";

export type ModuleField = { name: string; label: string; type: "text" | "number" | "date" | "select"; required?: boolean };
export type ErpModule = { key: ErpModuleKey; label: string; description: string; table: string; fields: ModuleField[]; workflows: string[] };

const defaultFields: ModuleField[] = [
  { name: "name_ar", label: "الاسم بالعربية", type: "text", required: true },
  { name: "status", label: "الحالة", type: "select" },
  { name: "company_id", label: "الشركة", type: "text", required: true },
  { name: "branch_id", label: "الفرع", type: "text" },
];

export const erpModules: ErpModule[] = [
  { key: "companies", label: "الشركات", description: "إدارة الكيانات القانونية والعملات والدول", table: "companies", fields: [{ name: "country", label: "الدولة", type: "select", required: true }, ...defaultFields], workflows: ["إنشاء شركة", "تعيين المدراء", "ربط أرقام ضريبية"] },
  { key: "branches", label: "الفروع", description: "تشغيل الفروع في السعودية والإمارات", table: "branches", fields: defaultFields, workflows: ["تحديد المدينة", "ربط المستودعات", "تفعيل نقاط البيع"] },
  { key: "warehouses", label: "المستودعات", description: "مستودعات متعددة وربطها بالفروع", table: "warehouses", fields: defaultFields, workflows: ["استلام", "صرف", "جرد", "تحويل"] },
  { key: "customers", label: "العملاء", description: "ملفات العملاء وحدود الائتمان وأرقام VAT", table: "customers", fields: [{ name: "credit_limit", label: "حد الائتمان", type: "number" }, ...defaultFields], workflows: ["اعتماد عميل", "تقييم ائتماني", "مطابقة أرصدة"] },
  { key: "customer_reconciliations", label: "مطابقة العملاء", description: "مطابقة كشوف العملاء والفواتير والمدفوعات", table: "customer_reconciliations", fields: [{ name: "customer_id", label: "العميل", type: "text", required: true }, { name: "difference_amount", label: "فرق المطابقة", type: "number" }, ...defaultFields], workflows: ["استيراد كشف", "اقتراح تسوية", "اعتماد الفروقات"] },
  { key: "suppliers", label: "الموردون", description: "عقود الموردين وحساباتهم وأرقام VAT", table: "suppliers", fields: defaultFields, workflows: ["اعتماد مورد", "مطابقة كشوف", "تقييم أداء"] },
  { key: "supplier_reconciliations", label: "مطابقة الموردين", description: "مطابقة فواتير الموردين والمدفوعات والإشعارات", table: "supplier_reconciliations", fields: [{ name: "supplier_id", label: "المورد", type: "text", required: true }, { name: "difference_amount", label: "فرق المطابقة", type: "number" }, ...defaultFields], workflows: ["مطابقة فاتورة", "تسوية دفعة", "اعتماد مالي"] },
  { key: "dubai_shipping_office", label: "مكتب شحن دبي", description: "إدارة شحنات دبي والتخليص والتكاليف", table: "dubai_shipping_shipments", fields: [{ name: "awb", label: "رقم الشحنة", type: "text", required: true }, { name: "eta", label: "تاريخ الوصول", type: "date" }, ...defaultFields], workflows: ["فتح شحنة", "تسجيل مصاريف", "ربط فاتورة مشتريات"] },
  { key: "inventory", label: "المخزون", description: "الأصناف والحركات والتحويلات", table: "inventory_items", fields: [{ name: "sku", label: "SKU", type: "text", required: true }, { name: "warehouse_id", label: "المستودع", type: "text" }, ...defaultFields], workflows: ["إضافة صنف", "جرد", "تسعير متوسط"] },
  { key: "sales", label: "المبيعات", description: "عروض وفواتير ومبيعات جوالة", table: "sales_invoices", fields: [{ name: "invoice_no", label: "رقم الفاتورة", type: "text", required: true }, { name: "total", label: "الإجمالي", type: "number" }, ...defaultFields], workflows: ["عرض سعر", "فاتورة ضريبية", "تحصيل"] },
  { key: "sales_quotations", label: "عروض الأسعار", description: "عروض أسعار مرتبطة بالعملاء وتتحول إلى فواتير", table: "sales_quotations", fields: [{ name: "quotation_no", label: "رقم العرض", type: "text", required: true }, { name: "customer_id", label: "العميل", type: "text" }, { name: "total", label: "الإجمالي", type: "number" }, ...defaultFields], workflows: ["إصدار عرض", "اعتماد", "تحويل إلى فاتورة"] },
  { key: "sales_returns", label: "مرتجعات المبيعات", description: "إرجاع أصناف العملاء وربطها بالمخزون والحسابات", table: "sales_returns", fields: [{ name: "return_no", label: "رقم المرتجع", type: "text", required: true }, { name: "customer_id", label: "العميل", type: "text" }, { name: "total", label: "الإجمالي", type: "number" }, ...defaultFields], workflows: ["طلب إرجاع", "فحص", "إضافة للمخزون"] },
  { key: "purchases", label: "المشتريات", description: "أوامر وفواتير مشتريات", table: "purchase_invoices", fields: [{ name: "invoice_no", label: "رقم فاتورة المورد", type: "text", required: true }, { name: "total", label: "الإجمالي", type: "number" }, ...defaultFields], workflows: ["طلب شراء", "استلام", "فاتورة مورد"] },
  { key: "purchase_returns", label: "مرتجعات المشتريات", description: "إرجاع مشتريات للموردين وتأثيرها على المخزون", table: "purchase_returns", fields: [{ name: "return_no", label: "رقم المرتجع", type: "text", required: true }, { name: "supplier_id", label: "المورد", type: "text" }, { name: "total", label: "الإجمالي", type: "number" }, ...defaultFields], workflows: ["طلب إرجاع", "اعتماد", "خصم من المخزون"] },
  { key: "accounting", label: "المحاسبة", description: "دليل الحسابات والقيود والتقارير", table: "journal_entries", fields: [{ name: "entry_date", label: "تاريخ القيد", type: "date" }, ...defaultFields], workflows: ["قيد يومية", "ترحيل", "إقفال فترة"] },
  { key: "cashboxes", label: "الصناديق", description: "إدارة الصناديق والنقدية والعهد", table: "cashboxes", fields: [{ name: "balance", label: "الرصيد", type: "number" }, ...defaultFields], workflows: ["استلام نقد", "صرف نقد", "جرد صندوق"] },
  { key: "main_vault", label: "الخزنة الرئيسية", description: "خزنة مركزية وسياسات تحويل للصناديق", table: "main_vaults", fields: [{ name: "balance", label: "رصيد الخزنة", type: "number" }, ...defaultFields], workflows: ["تغذية صندوق", "توريد بنك", "جرد رئيسي"] },
  { key: "banks", label: "البنوك", description: "الحسابات البنكية والتسويات", table: "bank_accounts", fields: [{ name: "iban", label: "IBAN", type: "text" }, { name: "balance", label: "الرصيد", type: "number" }, ...defaultFields], workflows: ["كشف بنك", "مطابقة", "تحويل"] },
  { key: "transfers", label: "التحويلات", description: "تحويلات مالية ومخزنية داخلية", table: "transfers", fields: [{ name: "amount", label: "المبلغ", type: "number" }, ...defaultFields], workflows: ["طلب تحويل", "موافقة", "تنفيذ"] },
  { key: "expenses", label: "المصروفات", description: "مطالبات ومراكز تكلفة", table: "expenses", fields: [{ name: "amount", label: "المبلغ", type: "number" }, ...defaultFields], workflows: ["مطالبة", "اعتماد", "صرف"] },
  { key: "payroll", label: "الرواتب", description: "الموظفون والرواتب والبدلات", table: "payroll_runs", fields: [{ name: "period_start", label: "بداية الفترة", type: "date" }, { name: "period_end", label: "نهاية الفترة", type: "date" }, ...defaultFields], workflows: ["مسير رواتب", "مراجعة", "دفع"] },
  { key: "projects", label: "المشاريع", description: "ميزانيات وتكاليف وربحية المشاريع", table: "projects", fields: [{ name: "budget", label: "الميزانية", type: "number" }, ...defaultFields], workflows: ["ميزانية", "تكلفة", "نسبة إنجاز"] },
  { key: "contracts", label: "العقود", description: "عقود العملاء والموردين والمشاريع", table: "contracts", fields: [{ name: "contract_no", label: "رقم العقد", type: "text", required: true }, { name: "contract_value", label: "قيمة العقد", type: "number" }, ...defaultFields], workflows: ["صياغة", "موافقة", "تجديد"] },
  { key: "investments", label: "الاستثمارات", description: "محافظ وعوائد وتقييمات", table: "investments", fields: [{ name: "fair_value", label: "القيمة العادلة", type: "number" }, ...defaultFields], workflows: ["شراء أصل", "تقييم", "توزيع عائد"] },
  { key: "attachments", label: "المرفقات", description: "أرشفة ملفات وفواتير", table: "attachments", fields: [{ name: "path", label: "مسار الملف", type: "text", required: true }, ...defaultFields], workflows: ["رفع", "تصنيف", "ربط بسند"] },
  { key: "notifications", label: "الإشعارات", description: "تنبيهات تشغيلية ومالية", table: "notifications", fields: defaultFields, workflows: ["تنبيه فوري", "تذكير", "تصعيد"] },
  { key: "approvals", label: "الموافقات", description: "مسارات اعتماد متعددة المستويات", table: "approvals", fields: [{ name: "subject_table", label: "الجدول", type: "text", required: true }, ...defaultFields], workflows: ["طلب", "مراجعة", "اعتماد/رفض"] },
  { key: "role_permissions", label: "الصلاحيات", description: "أدوار المستخدمين وصلاحيات الشاشات", table: "role_permissions", fields: [{ name: "role", label: "الدور", type: "select", required: true }, { name: "permission", label: "الصلاحية", type: "text", required: true }, ...defaultFields], workflows: ["منح صلاحية", "مراجعة أمنية", "تعطيل"] },
  { key: "activity_logs", label: "سجل التدقيق", description: "تتبع تدقيق كامل لكل عملية", table: "activity_logs", fields: [{ name: "action", label: "الإجراء", type: "text", required: true }, ...defaultFields], workflows: ["تسجيل تلقائي", "بحث", "تصدير"] },
  { key: "mobile_sales", label: "مندوبو المبيعات الجوالة", description: "زيارات ومبيعات وتحصيل المندوبين", table: "mobile_sales_representatives", fields: [{ name: "employee_id", label: "الموظف", type: "text" }, { name: "territory", label: "المنطقة", type: "text" }, { name: "target_amount", label: "المستهدف", type: "number" }, ...defaultFields], workflows: ["خط سير", "زيارة", "تحصيل", "رفع مستندات"] },
  { key: "ai_discrepancy_analysis", label: "تحليل الفروقات بالذكاء الاصطناعي", description: "كشف فروقات أرصدة ومخزون وضريبة واقتراح أسباب", table: "ai_discrepancy_findings", fields: [{ name: "severity", label: "الخطورة", type: "select" }, { name: "difference_amount", label: "قيمة الفرق", type: "number" }, ...defaultFields], workflows: ["تحليل", "اقتراح سبب", "فتح مهمة"] },
  { key: "ai_analytics", label: "تحليلات الذكاء الاصطناعي", description: "تنبؤات الطلب والتدفق النقدي", table: "ai_insights", fields: [{ name: "confidence", label: "الثقة", type: "number" }, ...defaultFields], workflows: ["تنبؤ", "توصية", "مراقبة"] },
  { key: "wealth_dashboard", label: "لوحة الثروة", description: "صافي الثروة وتوزيع الأصول والالتزامات", table: "wealth_snapshots", fields: [{ name: "assets", label: "الأصول", type: "number" }, { name: "liabilities", label: "الالتزامات", type: "number" }, ...defaultFields], workflows: ["تجميع أصول", "تقييم", "عرض صافي الثروة"] },
  { key: "backup_jobs", label: "النسخ الاحتياطي", description: "تصدير واستعادة بيانات الشركة بصيغة JSON/ZIP", table: "backup_jobs", fields: [{ name: "job_type", label: "نوع العملية", type: "select", required: true }, { name: "file_name", label: "اسم الملف", type: "text" }, ...defaultFields], workflows: ["تصدير", "تحقق", "استعادة"] },
  { key: "import_jobs", label: "استيراد ERP", description: "استيراد CSV/Excel من أنظمة ERP خارجية مع سجل أخطاء", table: "import_jobs", fields: [{ name: "source_system", label: "النظام المصدر", type: "text" }, { name: "target_table", label: "الجدول الهدف", type: "text", required: true }, ...defaultFields], workflows: ["رفع ملف", "مطابقة أعمدة", "اعتماد استيراد"] },
  { key: "multi_vat", label: "ضريبة متعددة للبائع/العميل", description: "إدارة أرقام VAT متعددة للشركات والعملاء والموردين", table: "party_vat_numbers", fields: [{ name: "vat_number", label: "الرقم الضريبي", type: "text", required: true }, { name: "party_type", label: "نوع الطرف", type: "select", required: true }, ...defaultFields], workflows: ["تحقق رقم", "تعيين افتراضي", "انتهاء صلاحية"] },
];

export const getModule = (key: string) => erpModules.find((module) => module.key === key);
